### PR TITLE
Search score by download counts

### PR DESCRIPTION
**Pull request by holyjak**
TODO Adjust the query structure / weights so that the effect is neither too weak nor does it push forward worse matches. Tricky! See `boost-by-downloads` at https://github.com/cljdoc/cljdoc/pull/359/files#diff-2ce74948e9ce83d10fbff231a0737ef7R121

via #308 

Note: This is how clojars incorporate download counts

### CODE REVIEW

**Comment by lread** [comment]
Hiya @holyjak! I am doing a maintenance pass on cljdoc, and the last set of deps I have not yet updated yet is lucene (current version is 9.0.0). 

You ok with me going ahead with the update? (Our API usage of lucene seems intact, I might add a few tests to check for any differences in results).

**Comment by lread** [comment]
Hmmm... I just noticed that clojars is also using Lucene. 
We can probably get inspiration from their hard work over there!

**Comment by holyjak** [comment]
Hi! Sorry for the late reply. Absolutely go ahead with the update!

And I am aware of the work at cljdoc and wish to steal from it. I just have so much on my plate that I an unable to prioritize it (also because I am afraid it would need a few days of exclusive focus to get done and I typically just have few hours here and there 😭) See https://github.com/cljdoc/cljdoc/issues/308#issuecomment-1021599750

**Comment by lread** [comment]
Thanks @holyjak I learned a lot from this PR!
It is now superseded by my little effort in #588, so closing this one.

**Comment by holyjak** [comment]
❤️

**Pull request closed without merging**
