### PR TITLE
Open search suggestion

### PR DESCRIPTION
**Pull request by green-coder**
Do not merge yet.

Implements the first part of the issue #223. Code review is welcome.

### CODE REVIEW

**Comment by green-coder** [comment]
@martinklepsch Some update on this PR:

My next step before I propose to merge this PR is to write a one-time small script that:
- downloads the list of the library names from clojars’ stats endpoints on the last `n` months,
- aggregate them and sum their download counts over the `n` months,
- keep only the `m` most downloaded libraries.

This list will be placed into an `edn` file, slurped into the server's RAM, and used in place of my current library list placeholder. This is intended to be a better temporary solution until we have a proper access to those stats in the DB of the server.

I may also adapt the suggestion's logic to take into account the number of downloads w.r.t. the way we choose the suggestion list.

**Comment by green-coder** [comment]
## WIP
image

Lucene on real-world data (15000+ library names)
The search does not take into account the library's popularity yet.

**Comment by martinklepsch** [comment]
Some thoughts on populating the Lucene index: 

- We'll also want to add artifacts from Maven Central, this could happen via hardcoded list (https://github.com/cljdoc/cljdoc/issues/200) or through some other mechanism. I might do some work on making that extensible very soon.
- To abstract over the different repository sources it might make sense to move the data into a uniform location. The `releases` table might be a good candidate. It has previously been used to track releases and trigger new documentation builds but it seems within scope to contain a list of all relevant artifacts.
  - The `releases` table will need to be extended by a repository identifier, `clojars`, `maven-central`, etc.
  - There's a bit of overlap with the `versions` table but I think it's best to defer unifying this.
- The data from the `releases` could then be synced with the Lucene index periodically. Later on it could make sense to integrate the project's description but let's wait with that until  #208 is resolved.

**Comment by holyjak** [comment]
FYI https://github.com/cljdoc/cljdoc/pull/306 has added a local search which could also be used to make the list of suggestions.

**Comment by holyjak** [comment]
Replaced by #316

**Pull request closed without merging**
