### PR TITLE
Add previously visited doc links on homepage

### LINKED ISSUE #282: Show list of last viewed projects on homepage
We track last viewed docs in localstorage and allow users to access those via `CMD-K`/`CTRL-K`:

screenshot 2019-03-01 at 11 36 46

This information could also be useful to show on the homepage to allow users to quickly navigate to documentation they recently used without typing/searching much.

Take a look at [`trackProjectOpened`](https://github.com/cljdoc/cljdoc/blob/01102870d1ecb05c577ef593621bd8c396c8baee/js/switcher.js#L21-L39) in `switcher.js` to understand how this information is stored and could be used.

### PR DESCRIPTION
**Pull request by rollacaster**
There's already an abandoned PR for this issue #399 so I thought I'd give it another try. I kept only the first commit of the old PR since merging the complete old PR  would be more effort.

After the page is loaded existing example links are replaced with the most recently visited doc links. If one of the initial example links is used it get's ignored.

Fixes #282

### CODE REVIEW

**Comment by martinklepsch** [comment]
Hi Thomas! Looking promising. I'd love to feature those a bit more prominently on the homepage as I think it's quite valuable and users might miss it when they just replace something that has been static for the last few years :D 

A sketch of what I could imagine this looking like:

> Read the rationale or pick up where you left off:
>
> - rum, _last viewed today_
> - m-parser, _last viewed 3d ago_
> - reitit, _last-viewed 20d ago_

Also very open to other designs/ideas, just trying to keep it simple :) I like the idea of showing the last time the docs were viewed because it implicitly tells the user what they're looking at (a reverse chronological list of the docs they've been looking at). The last-viewed data isn't currently in local storage though 😅 

Screen Shot 2021-10-04 at 21 16 02

I'm ok merging this as is but if you're down to hack on this a bit more, I hope these pointers are helpful :)

**Comment by rollacaster** [comment]
Hi Martin! You're right probably no one will notice the change in the current design, I'll make it more prominent 👍 

and thanks for the invite 🙂

**Comment by rollacaster** [comment]
Updated the UI + Showing last view time

image

**Review by martinklepsch — COMMENTED** [review]
This looks *really* great! I wonder if we should just remove the "Read the rationale..." thing once you visited some documentation? What do you think?

**Comment by rollacaster** [comment]
"Read the rationale..."  is now removed after at least three doc pages have been visited. 

If it's removed earlier it could be confusing, e.g. you visit cljdoc for the first time and decide to explore it using the examples. You click on the first example and then back, now the other examples are gone. (If we remove it earlier)

**Review by martinklepsch — APPROVED** [review]

**Pull request merged**
