### PR TITLE
Make a clear next action on a successful build.

### LINKED ISSUE #204: Make a very clear next action once a build has completed
When watching a build happen (e.g. https://cljdoc.org/builds/6561), at the end of the build, there isn't a single clear next action to take. One idea would be to add a button like this:

screenshot of google chrome 13-11-18 10-33-28 am

```html
<a class="f6 link dim ph3 pv2 mb2 dib white bg-blue" href="#0">Go to new documentation</a>
```

Styling and copy both need some work, but I've often felt when I'm looking at a build, "Ok, now what?" once it has finished.

Possibly another thing to do would be to include a big green tick/red cross on the last build step so people know that the process has completed.

### PR DESCRIPTION
**Pull request by corasaurus-hex**
Uses Wikipedia's capitalization rules for the button text:
https://titlecaseconverter.com/

Mimics the button format on the homepage and uses the styles suggested
in the issue.

Fixes #204 

Here's what it looks like when rendered on success:

20210804000133-k2e7j-cljdoc build #2

**NOTE:** the red box was added by me in post, for emphasis

### CODE REVIEW

**Comment by corasaurus-hex** [comment]
The contributor guidelines suggested completing a "good first issue" before biting off a larger chunk of work so here we are!

**Comment by martinklepsch** [comment]
Looks great 🚀  lets ship it! :)

**Review by martinklepsch — APPROVED** [review]

**Comment by corasaurus-hex** [comment]
Thanks, @martinklepsch!

**Comment by martinklepsch** [comment]
And it's deployed 👍  https://cljdoc.org/builds/47287

**Comment by lread** [comment]
Nice! And welcome to the cljdoc dev team @corasaurus-hex!

**Pull request merged**
