### PR TITLE
asciidoc formatting

### LINKED ISSUE #321: Render AsciiDoc code callouts
**Current behaviour**
cljdoc renders the following asciidoc callouts:

```asciidoc
[source,clojure]
----
;; some sweet clojure code

(defn hello-earthling
  "Greet an earthling in a believable way."  ;; <1>
  [name]
  (println "Hello earthling " (uppercase name))) ;; <2>
----
<1> a docstring comes before the arguments
<2> check with an earthling if uppercasing is soothing
```
like so:
image

As you can see the callouts rendered as (1) and (2) in the code do not catch the eye very well.

**Desired behavior**
The asciidoctor user manual shows callouts  rendered as icons, and so does the browser extension renderer:
image

The callouts rendered as icons are much easier to see.
(Ignore the fact that clojure code is not syntax highlighted here, cljdoc will continue to syntax highlight)

### PR DESCRIPTION
**Pull request by lread**
- fixed formatting for tables, admonitions, code callouts, content titles,
toc title
- upgraded highlightjs to current version
- now including highlighjs support for asciidoc as we are likely to include
asciidoc snippets in our user guides.
- asciidoc compatible v4.7.0 of font-awesome added
  - this was not required for our current admonitions or callouts but allows
  checkboxes and other icons to render properly.
  - decided on hosting this ourselves instead of going CDN route because CDN
  route seems to require account setup with font awesome?
- asciidoc css is now brought in by sass generated `cljdoc-asciidoc.css`
  - we use the same base sass that asciidoctor does for its default stylesheet
  which comes from https://github.com/asciidoctor/asciidoctor-stylesheet-factory
  - we take advantage of tachyons variable to encourage us to stick with
  tachyons stylings when we can
  - noticed some random styling issues in addition to ones reported in git
  issues and provided fixes - see `resources/public/sass/cljcdoc-asciidoc.scss`
  for details.
- offline support
  - includes new assets
  - now styles asciidoc documents (was not doing this before)
- see `resources/public/sass/README.md` for build instructions and further
details

Out of scope for this commit, but to consider:
- move remainder of styling in `cljdoc.css` to sass.  Benefits
  - specify tachyons styling elements by name
  - keeping css styling in one spot.
- include sass building in greater cljdoc build. It is currently a manually
invoked process.
- introduce auto-reloading of css and sass while developing ala figwheel main
or similar.
- include images in offline bundle

fixes #321 #322 #323 #324 #327

### CODE REVIEW

**Comment by martinklepsch** [comment]
Thanks Lee! I think making the formatting more consistent is great but I'm a little worried about the increased complexity by adding SASS to the build steps. Is there a way we could achieve proper formatting and offline support without bringing this tooling into the project?

Also it seems there is a CDN for font-awesome: https://www.bootstrapcdn.com/fontawesome/ ? 

If you've squashed this commit from multiple commits, please consider maintaining commit history for pull requests. We can squash using GitHubs UI and the commit history can help reviewers. :)

**Comment by lread** [comment]
Thanks for reviewing @martinklepsch!

I agree that adding SASS is a reasonable concern.  I started without it and found that I was spending too much time handcrafting hard to maintain css for asciidoc content. Using the very same  base that the asciidoctor team uses for styling html made for a much more pleasant and straightforward styling experience.

I expect that changing styling for asciidoc won’t happen very frequently and doesn’t absolutely need to be part of main build.

That said, if anyone else has other ideas, I’ve got an open mind.

Thanks for the CDN for font awesome, I’ll switch to that.  If the commit still looks heavy after that, I’ll see if I can split it to multiple commits to tell the story of the change better.

**Comment by lread** [comment]
Hey @martinklepsch, I managed to switch over to CDN for font-awesome.  If you look at files changed, I think you'll find this much less overwhelming to review.

To give you an idea of the kind of css involved, look at the sass generated [asciidoc.css](https://github.com/cljdoc/cljdoc/blob/428f171cde3bce1215c25e15826a58752f1f7ab0/resources/public/cljdoc-asciidoc.css) and compare that to the relative simplicity of the sass source we would need to maintain [cljdoc-asciidoc.scss](https://github.com/cljdoc/cljdoc/blob/428f171cde3bce1215c25e15826a58752f1f7ab0/resources/sass/cljdoc-asciidoc.scss) and [settings/_cljdoc-asciidoc.scss](https://github.com/cljdoc/cljdoc/blob/428f171cde3bce1215c25e15826a58752f1f7ab0/resources/sass/settings/_cljdoc-asciidoc.scss)

**Comment by martinklepsch** [comment]
I'll try to get around to test this tomorrow. 

Some notes to myself:

- explore if we could get rid of the ruby dependency by using https://github.com/sass/node-sass
- we have npm run stuff for the JS building, maybe we can combine these things using https://www.npmjs.com/package/concurrently
- maybe we can pull in tachyons etc via npm
- normalize.css seems to be duplicated (part of asciidoc but also part of tachyons)
- check that icons really improve things and are visually consistent with cljdoc's "style"
- consider combining all css 
- consider introducing a Makefile for the various make steps outlined in the "Running cljdoc locally" docs

**Comment by lread** [comment]
Another option is to separate out the generation of the the asciidoc.css to a separate project. It might make seem more like a specialized task and make it less tempting to try to make it conform to tooling in cljdoc.

One thing I found helpful in my testing was cljoc-exerciser. It includes the entire asciidoctor manual which is a very thorough visual testbed.

**Comment by lread** [comment]
One other option I thought of is to write a [custom asciidoctor backend](https://asciidoctor.org/docs/user-manual/#custom-backends).

Might be worth a deeper look to see how complicated it would be.  This might allow cljdoc to specify its asciidoctor formatting directly to elements via tachyons styles.

**Comment by lread** [comment]
@martinklepsch, I think the important question is: What do we want asciidoctor documents to look like when presented by cljdoc?  Internal implementation details are much less important.

My strong preference is to support the visual richness of asciidoctor.  That's one of the main reasons why people write their docs in asciidoc format is it not?

**Comment by lread** [comment]
I updated https://github.com/cljdoc/cljdoc-exerciser to allow use to more easily compare [CommonMark formatting](https://cljdoc.org/d/lread/cljdoc-exerciser/1.0.25/doc/document-tests/commonmark-features) with [AsciiDoc formatting](https://cljdoc.org/d/lread/cljdoc-exerciser/1.0.25/doc/document-tests/asciidoctor-features).

**Comment by lread** [comment]
This is stale. I'll start fresh if when I take this up again.

**Pull request closed without merging**
